# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=0, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
