# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0004_auto_20170509_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
